config/routes.rb
Rails.application.routes.draw do
  get 'todos/create'

  resources :categories do
  	resources :todos
  end
  get 'categories/index'
  root 'categories#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@category = Category.all.order('created_at DESC')
  end


  def new 
    @category = Category.new
  end

  def create
  	@category = Category.new(post_params)
    if @category.save
      redirect_to @category
    else 
      render 'new'
    end
  end

  def show
  	@category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(params[:category].permit(:name))
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end
  private
  	def post_params
  		params.require(:category).permit(:name)
  	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def create
  	@category = Category.find(params[:category_id])
  	@todo = @category.todos.create(params[:todo].permit(:description, :level))
  	redirect_to category_path(@category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
	<p>
	<%=f.label :name%>
	<%=f.text_field :name %>
	</p>
	<p>S
		<%= f.submit %>
	</p>
<%end%>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<% @category.each do |category| %>
<div class="post_wrapper"></div>
	<h2 class="title"><%= link_to category.name, category%></h2>
<%end%>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="title">
	<%= @category.name %>
</h1>
<p class="date">
	Submitted  <%= time_ago_in_words(@category.created_at) %> Ago
	| <%= link_to 'Edit', edit_category_path(@category) %>
	| <%= link_to 'Delete', category_path(@category), method: :delete, data: {confirm: 'Really?'}%>
</p>
<div>
	<h2> <%= @category.todos.count %>Todos</h2>
	<%= render @category.todos %>
	<h3>Add a Todo:</h3>
	<%= render "todos/form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UXEx1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="sidebar">
  	<ul>
  		<li class="category">Website</li>
  		<li><%= link_to "Categories", root_path%></li>
  		<li>About</li>
  	</ul>	
  	<p class="sign_in">Log in</p>
  </div>
  <div id="main_content">
  	<div id="header">
  		<p>All Posts</p>
  		<a href="/categories/new"><button class="button">New Category</button></a>
  	</div>
  	    <%= yield %>
  </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for([@category, @category.todos.build]) do |f| %>
	<p>
		<%= f.label :description %> <br>
		<%= f.text_field :level %>
	</p>
	<%= f.submit %>
<% end %>

app/views/todos/_todos.html.erb
<div class="todo clearfix">
	<div class="todo_content">
		<p class="todo_desc"> <%=todo.description%></p>
		<p class="todo_level"><%=todo.level%></p>
	</div>
</div>

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>